// The corpus the fuse.js oracle is generated from.
//
// Deliberately shaped like a real command palette: short verb-object names,
// overlapping words, a few long names, some entries with subtitles and some
// without, and keyword lists of varying length. The Dart port has to reproduce
// fuse's ranking over exactly this data.

export const actions = [
  { id: 'a01', name: 'Toggle theme', keywords: 'dark,light,appearance', subtitle: 'Switch between light and dark' },
  { id: 'a02', name: 'Set theme to dark', keywords: 'night', subtitle: 'Always use the dark theme' },
  { id: 'a03', name: 'Set theme to light', keywords: 'day', subtitle: 'Always use the light theme' },
  { id: 'a04', name: 'Set theme to system', keywords: 'auto', subtitle: 'Follow the operating system' },
  { id: 'a05', name: 'Open settings', keywords: 'preferences,config', subtitle: 'Application settings' },
  { id: 'a06', name: 'Open keyboard shortcuts', keywords: 'keybindings,hotkeys', subtitle: '' },
  { id: 'a07', name: 'Open file', keywords: 'load', subtitle: 'Open a file from disk' },
  { id: 'a08', name: 'Open recent file', keywords: 'history', subtitle: '' },
  { id: 'a09', name: 'Open folder', keywords: 'directory', subtitle: '' },
  { id: 'a10', name: 'Save', keywords: 'write,persist', subtitle: 'Save the current file' },
  { id: 'a11', name: 'Save as', keywords: 'write,copy', subtitle: 'Save under a new name' },
  { id: 'a12', name: 'Save all', keywords: 'write', subtitle: '' },
  { id: 'a13', name: 'Close file', keywords: '', subtitle: '' },
  { id: 'a14', name: 'Close all files', keywords: '', subtitle: '' },
  { id: 'a15', name: 'Close window', keywords: 'quit', subtitle: '' },
  { id: 'a16', name: 'Git status', keywords: 'vcs,source control', subtitle: 'Show the working tree status' },
  { id: 'a17', name: 'Git commit', keywords: 'vcs,save', subtitle: 'Record changes to the repository' },
  { id: 'a18', name: 'Git push', keywords: 'vcs,upload', subtitle: 'Push commits to the remote' },
  { id: 'a19', name: 'Git pull', keywords: 'vcs,download,fetch', subtitle: 'Fetch and integrate' },
  { id: 'a20', name: 'Git checkout branch', keywords: 'vcs,switch', subtitle: '' },
  { id: 'a21', name: 'Git create branch', keywords: 'vcs,new', subtitle: '' },
  { id: 'a22', name: 'Git stash changes', keywords: 'vcs', subtitle: '' },
  { id: 'a23', name: 'Search in files', keywords: 'find,grep,ripgrep', subtitle: 'Search across the project' },
  { id: 'a24', name: 'Search and replace', keywords: 'find,substitute', subtitle: '' },
  { id: 'a25', name: 'Go to line', keywords: 'jump,navigate', subtitle: '' },
  { id: 'a26', name: 'Go to symbol', keywords: 'jump,navigate,definition', subtitle: '' },
  { id: 'a27', name: 'Go to definition', keywords: 'jump,navigate', subtitle: '' },
  { id: 'a28', name: 'Go back', keywords: 'navigate,history', subtitle: '' },
  { id: 'a29', name: 'Go forward', keywords: 'navigate,history', subtitle: '' },
  { id: 'a30', name: 'Format document', keywords: 'prettier,beautify', subtitle: 'Reformat the whole file' },
  { id: 'a31', name: 'Format selection', keywords: 'prettier', subtitle: '' },
  { id: 'a32', name: 'Toggle sidebar', keywords: 'panel,layout', subtitle: '' },
  { id: 'a33', name: 'Toggle terminal', keywords: 'console,shell', subtitle: 'Show or hide the terminal' },
  { id: 'a34', name: 'Toggle full screen', keywords: 'maximise,layout', subtitle: '' },
  { id: 'a35', name: 'Toggle word wrap', keywords: 'layout', subtitle: '' },
  { id: 'a36', name: 'Zoom in', keywords: 'bigger,scale', subtitle: '' },
  { id: 'a37', name: 'Zoom out', keywords: 'smaller,scale', subtitle: '' },
  { id: 'a38', name: 'Reset zoom', keywords: 'scale', subtitle: '' },
  { id: 'a39', name: 'New file', keywords: 'create', subtitle: '' },
  { id: 'a40', name: 'New window', keywords: 'create', subtitle: '' },
  { id: 'a41', name: 'New terminal', keywords: 'create,shell', subtitle: '' },
  { id: 'a42', name: 'Rename symbol', keywords: 'refactor', subtitle: '' },
  { id: 'a43', name: 'Extract method', keywords: 'refactor', subtitle: '' },
  { id: 'a44', name: 'Run all tests', keywords: 'test,check', subtitle: 'Run the entire test suite' },
  { id: 'a45', name: 'Run test at cursor', keywords: 'test', subtitle: '' },
  { id: 'a46', name: 'Debug: start', keywords: 'run,breakpoint', subtitle: '' },
  { id: 'a47', name: 'Debug: stop', keywords: 'run', subtitle: '' },
  { id: 'a48', name: 'Toggle breakpoint', keywords: 'debug', subtitle: '' },
  { id: 'a49', name: 'Copy path of active file', keywords: 'clipboard', subtitle: '' },
  { id: 'a50', name: 'Reveal in file explorer', keywords: 'finder,show', subtitle: '' },
  { id: 'a51', name: 'Install extension', keywords: 'plugin,addon', subtitle: '' },
  { id: 'a52', name: 'Reload window', keywords: 'restart,refresh', subtitle: '' },
  { id: 'a53', name: 'Report an issue', keywords: 'bug,feedback', subtitle: '' },
  { id: 'a54', name: 'Check for updates', keywords: 'upgrade', subtitle: '' },
  { id: 'a55', name: 'Sign out', keywords: 'logout,account', subtitle: '' },
  { id: 'a56', name: 'Switch account', keywords: 'profile,user', subtitle: '' },
  { id: 'a57', name: 'Documentation', keywords: 'docs,help,manual', subtitle: 'Read the documentation' },
  { id: 'a58', name: 'Keyboard shortcuts reference', keywords: 'help', subtitle: '' },
  { id: 'a59', name: 'Contact support', keywords: 'help,email', subtitle: '' },
  { id: 'a60', name: 'Clear cache and reload the application window', keywords: 'reset,restart', subtitle: 'A deliberately long name' },
];

export const queries = [
  't', 'th', 'the', 'them', 'theme', 'themes',
  'dark', 'lite', 'light',
  'g', 'gi', 'git', 'gits', 'gitp', 'git p', 'push', 'psh',
  'save', 'sav', 'svae', 'sve',
  'open', 'opn', 'op',
  'go', 'goto', 'go to', 'line', 'symbol', 'def',
  'toggle', 'tggle', 'togle',
  'new', 'nw',
  'zoom', 'zm',
  'term', 'terminal', 'shell', 'console',
  'test', 'tst', 'run',
  'help', 'docs', 'doc',
  'file', 'fil', 'flie',
  'window', 'win', 'wndw',
  'refactor', 'rename',
  'settings', 'prefs', 'preferences', 'config',
  'clear cache', 'reload',
  'xyzzy', 'qqqq',
];
